### ISSUE TITLE
Replace old Google+ links

### ISSUE THREAD

**Issue by TrianguloY** [TrianguloY/LightningLauncher#15]
Replace all the obsolete links, including the Google+ and possibly more.

Not sure yet what to replace them with...

**Comment by SnowVolf** [comment]
I looked at the links that are inside the project. There are no links to Google+. The other links that are available to the user do not need to be replaced

**Comment by TrianguloY** [comment]
Hmm, in that case I guess only the strings need to be updated, at least the "Lightning Launcher on Google+" from the main lighting settings.

I remember a report in the forum asking to replace some links, and last time I checked I think I spotted a couple that should be. Let me review them myself, perhaps I'm misremembering.
