### ISSUE TITLE
White shortcuts background on dark theme

### ISSUE THREAD

**Issue by TrianguloY** [TrianguloY/LightningLauncher#17]
If the app is configured to have a dark theme (long tap -> settings -> lightning -> general -> settings screen style) the "Select a shortcut" screen (long tap -> [+] -> shortcut) is still white.

Addendum: the setting should be renamed to just 'Lightning screen style' or 'Lightning theme'

**Comment by SnowVolf** [comment]
This dialog is not part of the application. It appears when launching Intent.ACTION_PICK_ACTIVITY. We can't affect its display

**Comment by TrianguloY** [comment]
Ah, ok. I tried to search just in case there was an intent extra or something to configure it, but doesn't seem like it.

Closed then. Thanks for checking!
